spring.datasource.url=jdbc:mysql://localhost:3306/billing_app
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/api/v1.0

aws.access.key=AKIAQPBSRGVXKUZJLMDA
aws.secret.key=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
aws.region=ap-south-1
aws.bucket.name=billing-software-krishnan07

jwt.secret.key=thisismysecretkeyfortheupcomingproject