spring.datasource.url=jdbc:mysql://localhost:3306/billing_app
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/api/v1.0
# serve uploaded files from the uploads/ folder on disk
spring.web.resources.static-locations=classpath:/static/,file:uploads/

jwt.secret.key=thisismysecretkeyfortheupcomingproject